# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhywyt/CSON/01_Test/01_Test.srcs/sources_1/ip/fetch_instruction_ROM/fetch_instruction_ROM.xci
# IP: The module: 'fetch_instruction_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhywyt/CSON/01_Test/01_Test.gen/sources_1/ip/fetch_instruction_ROM/fetch_instruction_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fetch_instruction_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/zhywyt/CSON/01_Test/01_Test.srcs/sources_1/ip/fetch_instruction_ROM/fetch_instruction_ROM.xci
# IP: The module: 'fetch_instruction_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhywyt/CSON/01_Test/01_Test.gen/sources_1/ip/fetch_instruction_ROM/fetch_instruction_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fetch_instruction_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
